/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magicalarena.app;

import magicalarena.app.IGameController;
import magicalarena.app.GameControls;

public class App {
    public static void main(String[] args) {
        System.out.println("Game Started!");
        IGameController gameController = new GameControls();
        gameController.playGame();
    }
}
